import AdminShell from '../components/AdminShell'
import { useEffect, useRef, useState } from 'react'
import { api } from '../lib/mockApi'
import { QRCodeCanvas } from 'qrcode.react'
import jsPDF from 'jspdf'
function genExamToken(sem='EX1'){const a='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';let c='';for(let i=0;i<6;i++) c+=a[Math.floor(Math.random()*a.length)];return `${sem}-${c}`}
export default function HallTickets(){
  const [students,setStudents]=useState([]); const [exams,setExams]=useState([]); const [sel,setSel]=useState({student_id:'',exam_id:''}); const [token,setToken]=useState(''); const qrRef=useRef(null)
  useEffect(()=>{(async()=>{setStudents(await api.listStudents()); setExams(await api.listExams())})()},[])
  const generate=async()=>{ if(!sel.student_id||!sel.exam_id) return alert('Select student & exam'); const exam=(await api.listExams()).find(x=>String(x.id)===String(sel.exam_id)); const sem=(exam?.title||'EX').split(' ')[0]; const tok=genExamToken(sem); setToken(tok); await api.upsertHallTicket({ student_id: sel.student_id, exam_id: sel.exam_id, token: tok })}
  const printPdf=async()=>{ const st=(await api.listStudents()).find(s=>s.student_id===sel.student_id); const ex=(await api.listExams()).find(x=>String(x.id)===String(sel.exam_id)); if(!st||!ex||!token) return alert('Generate first'); const doc=new jsPDF({unit:'pt',format:'a4'}); doc.setFontSize(16); doc.text('Vijayam College of Arts & Science — Chennai',40,40); doc.roundedRect(32,56,530,300,8,8); doc.setFontSize(18); doc.text('Hall Ticket',40,80); doc.setFontSize(12); doc.text(`Name: ${st.full_name}`,48,110); doc.text(`Permanent HT No: ${st.hall_ticket_no}`,48,132); doc.text(`Exam: ${ex.title}`,48,154); doc.text(`Date: ${ex.date}  Time: ${ex.time}`,48,176); doc.text(`Venue: ${ex.venue}`,48,198); doc.setTextColor('#1FAA59'); doc.text(`Encoded Token: ${token}`,48,220); doc.setTextColor('#000'); const canvas=qrRef.current?.querySelector('canvas'); if(canvas){const img=canvas.toDataURL('image/png'); doc.addImage(img,'PNG',420,110,120,120)}; doc.setFontSize(11); const rules=['Carry a valid photo ID.','Report 30 minutes before the exam.','No mobile phones/smart devices.','Use permitted stationery only.']; let y=250; doc.text('Rules:',48,y); y+=16; rules.forEach(r=>{ doc.text(`• ${r}`,56,y); y+=16; }); doc.text('Signature (Controller of Examinations) ____________________',48,340); doc.save(`HallTicket_${st.hall_ticket_no}_${ex.title}.pdf`)}
  return (<AdminShell><h2 className="fw-bold mb-3">Hall Ticket Generator</h2><div className="card card-soft p-3"><div className="row g-2"><div className="col-md-4"><select className="form-select" value={sel.student_id} onChange={e=>setSel({...sel,student_id:e.target.value})}><option value="">Select Student</option>{students.map(s=>(<option key={s.student_id} value={s.student_id}>{s.student_id} — {s.full_name}</option>))}</select></div><div className="col-md-4"><select className="form-select" value={sel.exam_id} onChange={e=>setSel({...sel,exam_id:e.target.value})}><option value="">Select Exam</option>{exams.map(x=>(<option key={x.id} value={x.id}>{x.title} ({x.date})</option>))}</select></div><div className="col-md-4"><button className="btn btn-brand w-100" onClick={generate}>Generate Token</button></div></div>{token&&(<div className="mt-3 p-3 border rounded" ref={qrRef}><div className="d-flex justify-content-between align-items-center"><div><div className="text-muted small">Encoded Token</div><div className="fw-bold">{token}</div></div><QRCodeCanvas value={token} size={128} includeMargin /></div><div className="mt-2 d-flex justify-content-end"><button className="btn btn-accent" onClick={printPdf}>Print / Download PDF</button></div></div>)}</div></AdminShell>)}
